---

# Role: bjornaru.i3gaps
# File: tasks/install.yml


- name: Check if i3-gaps is installed
  stat:
    path: /usr/bin/i3
  register: i3

- name: Install build dependencies
  become: yes
  package:
    name: '{{ i3gaps_build_packages }}'
    state: '{{ i3gaps_build_packages_state }}'

- name: Clone i3-gaps git repo
  git:
    repo: https://www.github.com/Airblader/i3
    dest: '{{ i3gaps_git_path }}'
    version: '{{ i3gaps_version }}'
  when: not i3.stat.exists

- name: Configure (autoreconf)
  command:
    chdir: "{{ i3gaps_git_path }}"
    cmd: autoreconf --force --install
    creates: /usr/bin/i3

- name: Remove build directory
  file:
    path: "{{ i3gaps_git_path }}/build"
    state: absent
  when: not i3.stat.exists

- name: Re-create build directory
  file:
    path: "{{ i3gaps_git_path }}/build"
    state: directory
    mode: 0777
  when: not i3.stat.exists

- name: Run configure
  command:
    chdir: "{{ i3gaps_git_path }}/build"
    cmd: ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
    creates: /usr/bin/i3

- name: Run make
  make:
    chdir: "{{ i3gaps_git_path }}/build"
  when: not i3.stat.exists

- name: Run make install
  make:
    chdir: "{{ i3gaps_git_path }}/build"
    target: install
  when: not i3.stat.exists

- name: Install extras
  become: yes
  package:
    name: '{{ i3gaps_extra_packages }}'
    state: '{{ i3gaps_extra_packages_state }}'
  when: install_i3gaps_extra_packages|bool

...
